name: Build Binaries

# Trigger workflow on push to main branch or on pull request
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, macos]
        arch: [amd64]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Build binary
      - name: Build binary
        run: |
          output="build/directory-diff-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
              output="$output.exe"
          fi
          mkdir -p build
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $output ./cmd/main.go

      # Step 4: Upload build artifacts
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/

